### ISSUE TITLE
Tests failing & 'dirent.h' file not found

### ISSUE THREAD

**Issue by zsolt-halo** [nowsecure/frida-cycript#5]
Hi, i have followed the steps you told with installing and compiling.
I also included android SDK to my path for the 'dx' executable.

This is what i get when i run 'make -j8'
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
  CC       libcycript_la-ConvertUTF.lo
  CXX      libcycript_la-Decode.lo
  CXX      libcycript_la-Driver.lo
  CXX      libcycript_la-Error.lo
  CXX      libcycript_la-Highlight.lo
  CXX      libcycript_la-Library.lo
  CXX      libcycript_la-Output.lo
  CXX      libcycript_la-Replace.lo
  CXX      libcycript_la-Syntax.lo
./Filter.sh Parser.ypp.in >Parser.ypp C Java Ruby Python ObjectiveC
./Filter.sh Scanner.lpp.in >Scanner.lpp C Java Ruby Python ObjectiveC
  CXX      sig/libcycript_la-parse.lo
  CXX      sig/libcycript_la-copy.lo
  CXX      libcycript_la-Complete.lo
  CXX      libcycript_la-Execute.lo
  CXX      Java/libcycript_la-Execute.lo
  CXX      Ruby/libcycript_la-Execute.lo
  CXX      Python/libcycript_la-Execute.lo
  CXX      ObjectiveC/libcycript_la-Output.lo
  CXX      ObjectiveC/libcycript_la-Replace.lo
  CXX      Console.o
g++ -g -O2 -std=c++11  -DCY_JAVA=1 -DCY_PYTHON=1 -DCY_OBJECTIVEC=1 -I./extra -o Analyze Analyze.cpp Error.cpp Output.cpp Replace.cpp Syntax.cpp -rpath /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib -Wno-bitwise-op-parentheses -Wno-dangling-else -Wno-logical-op-parentheses
cd Class; jar cf ../libcycript.jar *
BISON_PKGDATADIR=../ext/toolchain/usr/share/bison ../ext/toolchain/usr/bin/bison-mac-x86_64 -v --report=state -Werror -o Parser.cpp Parser.ypp
/usr/bin/flex --full --ecs -o Scanner.cpp -T Scanner.lpp 2>Scanner.output || (grep -F 'Scanner.lpp:' Scanner.output; false)
perl -pi -e 's/yytranslate_ \(yylex \(/(yylex_ (/g' Parser.cpp
  CXX      libcycript_la-Parser.lo
  CXX      libcycript_la-Scanner.lo
./Analyze Analysis.cpp g++ -I/usr/local/opt/readline/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fvisibility=hidden  -fobjc-exceptions -g -O2 -std=gnu++11 -Werror -Wno-deprecated-declarations -Wno-dangling-else -Wno-empty-body -Wno-overloaded-virtual -Wno-parentheses -Wno-tautological-undefined-compare -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -DCY_JAVA=1 -DCY_PYTHON=1 -DCY_OBJECTIVEC=1  >Bridge.def
'dirent.h' file not found
cat ./Bridge.old >>Bridge.def
./libcycript.py 1 libcycript.db ../ext <Bridge.def
  CXXLD    libcycript.la
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
copying selected object files to avoid basename conflicts...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt1-libcycript_la-Execute.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt2-libcycript_la-Execute.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt3-libcycript_la-Execute.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt1-libcycript_la-Execute.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt2-libcycript_la-Execute.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcycript.a(lt3-libcycript_la-Execute.o) has no symbols
  CXXLD    cycript
make[2]: Nothing to be done for `all-am'.
```

Also, when i run 'npm run test'

```
> cycript-test@1.0.0 test /Users/zsh/mobile/tools/frida-cycript/test
> DYLD_LIBRARY_PATH=$(pwd)/../src/.libs node node_modules/mocha/bin/_mocha .



  Types
    ✓ should support primitive types
    ✓ should support `new` semantics
    1) should support pretty-printing function pointers
    ✓ should support pointer casting
    ✓ should support declaring functions
    2) should source types from the database
    3) should support structs
    ✓ should support arrays
    ✓ should support C strings
    4) should support completion of database types
    ✓ should support Objective-C types
    ✓ should support Objective-C literals
    ✓ should keep Objective-C objects alive until GCed
    ✓ should support NSString objects seamlessly
    ✓ should support NSArray objects seamlessly
    ✓ should support NSDictionary objects seamlessly
    5) should support calling a selector
    6) should support Objective-C completion
    ✓ should support symbol lookups
    7) should support hooking functions
    8) should support swizzling methods


  13 passing (489ms)
  8 failing

  1) Types should support pretty-printing function pointers:

      AssertionError: expected 'throw new ReferenceError("dlopen is not defined")' to be '(extern "C" void *dlopen(char const*, int))'
      + expected - actual

      -throw new ReferenceError("dlopen is not defined")
      +(extern "C" void *dlopen(char const*, int))
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:26:38)

  2) Types should source types from the database:

      AssertionError: expected 'throw new ReferenceError("fopen is not defined")' to be '(extern "C" struct __sFILE *fopen(char const*, char const*))'
      + expected - actual

      -throw new ReferenceError("fopen is not defined")
      +(extern "C" struct __sFILE *fopen(char const*, char const*))
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:42:37)

  3) Types should support structs:

      AssertionError: expected 'throw new ReferenceError("Dl_info is not defined")' to be '&{dli_fname:null,dli_fbase:null,dli_sname:null,dli_saddr:null}'
      + expected - actual

      -throw new ReferenceError("Dl_info is not defined")
      +&{dli_fname:null,dli_fbase:null,dli_sname:null,dli_saddr:null}
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:57:53)

  4) Types should support completion of database types:
     AssertionError: expected '[]' to contain 'memcpy'
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:93:57)

  5) Types should support calling a selector:

      AssertionError: expected 'throw new ReferenceError("capitalize is not defined")' to be '@"Hello"'
      + expected - actual

      -throw new ReferenceError("capitalize is not defined")
      +@"Hello"
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:159:57)

  6) Types should support Objective-C completion:

      AssertionError: expected 'throw new ReferenceError("object_getClass is not defined")' to be '["cy$complete"]'
      + expected - actual

      -throw new ReferenceError("object_getClass is not defined")
      +["cy$complete"]
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:165:95)

  7) Types should support hooking functions:

      AssertionError: expected 'throw new ReferenceError("fopen is not defined")' to be '[["/etc/hosts","r"],["/etc/passwd","r"]]'
      + expected - actual

      -throw new ReferenceError("fopen is not defined")
      +[["/etc/hosts","r"],["/etc/passwd","r"]]
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:194:15)

  8) Types should support swizzling methods:
     AssertionError: expected 'throw new ReferenceError("sel_registerName is not defined")' to match /#"<NSObject: 0x[0-9a-f]+> \(of doom\)"/
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Context.<anonymous> (types.js:206:15)




npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! cycript-test@1.0.0 test: `DYLD_LIBRARY_PATH=$(pwd)/../src/.libs node node_modules/mocha/bin/_mocha .`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the cycript-test@1.0.0 test script 'DYLD_LIBRARY_PATH=$(pwd)/../src/.libs node node_modules/mocha/bin/_mocha .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cycript-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DYLD_LIBRARY_PATH=$(pwd)/../src/.libs node node_modules/mocha/bin/_mocha .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cycript-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cycript-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zsh/mobile/tools/frida-cycript/test/npm-debug.log
```

So i got 8 tests failing out of 21. Is this a 'works as designed behaviour' or the result of something else?

Regards,
zs

**Comment by oleavr** [comment]
This is indeed a regression. Looks like it's triggered by newer versions of libclang bundled with Xcode.
